In [ ]:
import numpy as np
import numbers
from itertools import combinations, permutations, chain

In [ ]:
def permn(x, m, FUN=None):
    if isinstance(x, numbers.Number):
        if isinstance(x, int) and x >= 0:
            x = range(1, x + 1)
        else:
            raise Exception("Positive integer or vector are allowed")            

    # Get each combination then apply permutations corresponding to that combination
    permutation = [permutations(combn) for combn in combinations(x, m)]
          
    # 2D list to 1D list
    permutation = chain.from_iterable(permutation) 
    
    if FUN:
        result = [FUN(i) for i in list(permutation)]
        return result
    else:
        return list(permutation)

In [ ]:
permn(4, 3)

[(1, 2, 3),
 (1, 3, 2),
 (2, 1, 3),
 (2, 3, 1),
 (3, 1, 2),
 (3, 2, 1),
 (1, 2, 4),
 (1, 4, 2),
 (2, 1, 4),
 (2, 4, 1),
 (4, 1, 2),
 (4, 2, 1),
 (1, 3, 4),
 (1, 4, 3),
 (3, 1, 4),
 (3, 4, 1),
 (4, 1, 3),
 (4, 3, 1),
 (2, 3, 4),
 (2, 4, 3),
 (3, 2, 4),
 (3, 4, 2),
 (4, 2, 3),
 (4, 3, 2)]

In [ ]:
permn([1,2,3,4], 3)

[(1, 2, 3),
 (1, 3, 2),
 (2, 1, 3),
 (2, 3, 1),
 (3, 1, 2),
 (3, 2, 1),
 (1, 2, 4),
 (1, 4, 2),
 (2, 1, 4),
 (2, 4, 1),
 (4, 1, 2),
 (4, 2, 1),
 (1, 3, 4),
 (1, 4, 3),
 (3, 1, 4),
 (3, 4, 1),
 (4, 1, 3),
 (4, 3, 1),
 (2, 3, 4),
 (2, 4, 3),
 (3, 2, 4),
 (3, 4, 2),
 (4, 2, 3),
 (4, 3, 2)]

In [ ]:
permn([1,2,3,4], 3, np.min)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]

In [ ]:
permn([1,2,3,4], 3, np.max)

[3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]

In [ ]:
permn([1,2,3,4],3, np.var)

[0.6666666666666666,
 0.6666666666666666,
 0.6666666666666666,
 0.6666666666666666,
 0.6666666666666666,
 0.6666666666666666,
 1.5555555555555554,
 1.5555555555555556,
 1.5555555555555554,
 1.5555555555555554,
 1.5555555555555556,
 1.5555555555555554,
 1.5555555555555554,
 1.5555555555555556,
 1.5555555555555554,
 1.5555555555555554,
 1.5555555555555556,
 1.5555555555555554,
 0.6666666666666666,
 0.6666666666666666,
 0.6666666666666666,
 0.6666666666666666,
 0.6666666666666666,
 0.6666666666666666]

In [ ]:
permn([1,2,3,4],3, np.std)

[0.816496580927726,
 0.816496580927726,
 0.816496580927726,
 0.816496580927726,
 0.816496580927726,
 0.816496580927726,
 1.247219128924647,
 1.247219128924647,
 1.247219128924647,
 1.247219128924647,
 1.247219128924647,
 1.247219128924647,
 1.247219128924647,
 1.247219128924647,
 1.247219128924647,
 1.247219128924647,
 1.247219128924647,
 1.247219128924647,
 0.816496580927726,
 0.816496580927726,
 0.816496580927726,
 0.816496580927726,
 0.816496580927726,
 0.816496580927726]

In [ ]:
permn([1,2,3,4],3,np.diag)

[array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]]),
 array([[1, 0, 0],
        [0, 3, 0],
        [0, 0, 2]]),
 array([[2, 0, 0],
        [0, 1, 0],
        [0, 0, 3]]),
 array([[2, 0, 0],
        [0, 3, 0],
        [0, 0, 1]]),
 array([[3, 0, 0],
        [0, 1, 0],
        [0, 0, 2]]),
 array([[3, 0, 0],
        [0, 2, 0],
        [0, 0, 1]]),
 array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 4]]),
 array([[1, 0, 0],
        [0, 4, 0],
        [0, 0, 2]]),
 array([[2, 0, 0],
        [0, 1, 0],
        [0, 0, 4]]),
 array([[2, 0, 0],
        [0, 4, 0],
        [0, 0, 1]]),
 array([[4, 0, 0],
        [0, 1, 0],
        [0, 0, 2]]),
 array([[4, 0, 0],
        [0, 2, 0],
        [0, 0, 1]]),
 array([[1, 0, 0],
        [0, 3, 0],
        [0, 0, 4]]),
 array([[1, 0, 0],
        [0, 4, 0],
        [0, 0, 3]]),
 array([[3, 0, 0],
        [0, 1, 0],
        [0, 0, 4]]),
 array([[3, 0, 0],
        [0, 4, 0],
        [0, 0, 1]]),
 array([[4, 0, 0],
        [0, 1, 0],
        [0, 0, 3]]